import { Inter } from 'next/font/google';
import './globals.css';
import { getServerSession } from 'next-auth/next';
import NextAuthProvider from './components/NextAuthProvider';
import { options } from './api/auth/[...nextauth]/options';
import NavMenu from './components/NavMenu';
import styles from './page.module.css';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(options);
  console.log('session layout===========', options);
  return (
    <html lang="en">
      <NextAuthProvider session={session}>
        <body className={inter.className}>
          <div className="main-menu">
            <NavMenu />
          </div>
          <main className={styles.main}>{children}</main>
        </body>
      </NextAuthProvider>
    </html>
  );
}
